### ISSUE TITLE
Release to pypi 

### ISSUE THREAD

**Issue by drcrallen** [metamx/pydruid#25]

**Comment by fjy** [comment]
:+1:

**Comment by drcrallen** [comment]
I'm hoping to be able to tackle this on 2015-07-24 assuming noone else can tackle it before then.

**Comment by xvrl** [comment]
done, released to https://github.com/metamx/pydruid/releases/tag/pydruid-0.2.2 to https://pypi.python.org/pypi/pydruid/0.2.2
