### ISSUE TITLE
Re-upload version 0.2.1 to pypi

### ISSUE THREAD

**Issue by fizyk** [metamx/pydruid#26]
It looks like releasing new version, you guys have removed 0.2.1 from pypi.

I'd ask you to re-upload that as we've have a strict dependency upgrade policy, and our requirements are locked against specific version of packages, including pydruid.

**Comment by xvrl** [comment]
@fizyk as far as I know 0.2.1 was never an official release. When I checked, it was hidden in pypi. The date on it was from before 0.2.0 was even released, so I'm not sure what it corresponds to. Maybe @dganguli can provide some background on what that old 0.2.1 corresponds to?

I removed the old 0.2.1 it the attempt to release version 0.2.1, the successor to 0.2.0, which I tagged last week, but pypi didn't allow uploading a different 0.2.1, so I had to bump up to 0.2.2.

**Comment by dganguli** [comment]
I believe 0.2.1 was a borked release and 0.2.0 was the first official pypi release.

**Comment by fizyk** [comment]
so... it's not possible to upload that borked version? it's been there for a long while...

**Comment by xvrl** [comment]
@fizyk If I remember correctly that old 0.2.1 was uploaded on 2014-04-03, and based on the git history, the code is identical to the first 0.2.0 release, the only differences are documentation and comments

**Comment by xvrl** [comment]
@fizyk If we can find someone who has the old 0.2.1 tarball, we can try re-uploading it using a different version number so it won't be too confusing, otherwise I would advise to just switch your code to use 0.2.0. Let us know if you are having issues with 0.2.0.

**Comment by fizyk** [comment]
ok then... let's just close it. We've pushed the upgrade down, my only concern is that if we'd ever had to downgrade the system, it would be a nightmare. Well... if it's identical to 0.2.0, we'll figure something out then...

**Comment by xvrl** [comment]
@fizyk sounds good, sorry again for the version mishap, please re-open if you're having issues with 0.2.0

**Comment by fizyk** [comment]
@xvrl do you guys have up-to-date changelog somewhere? betweem the 0.2.0/1 and 0.2.2 we've got some simple integration tests failing, and would like to see some changes synopsis.

**Comment by xvrl** [comment]
@fizyk Here's the list of PRs that got merged between 0.2.0 and 0.2.2. Most of those are bugfixes, support for additional query types and unit tests.
https://github.com/metamx/pydruid/pulls?q=is%3Apr+is%3Aclosed+milestone%3A0.2.2

If any of those broke anything, would you mind filing an issue that reproduces the problem?
